### ISSUE TITLE
load tests interfere with eachother

### ISSUE THREAD

**Issue by jamie256** [whylabs/langkit#109]
e.g.

Running the following passes:
```
poetry run pytest langkit/tests/test_injections.py -o log_level=INFO -o log_cli=true --load
```
but this fails some of the test_injections.py tests:
```
poetry run pytest langkit/tests -o log_level=INFO -o log_cli=true --load
```

Suspect we need some test setup/tear down helpers to reset udfs between tests. Might need more isolated ways of testing the various UDF configs so they don't affect other tests.

**Comment by richard-rogers** [comment]
I think this is an actual LangKit/whylogs... bug? design issue?

The `regexes.py` module registers a `UdfMetric` for all columns of string type. `injections.py` registers a `UdfMetric` for the `_prompt` column (by name). A column can only have one `UdfMetric` instance, so there's a race condition for which `UdfMetric` gets applied to the `_prompt` column. The registration mechanism will unify all the metric UDFs registered to the same column name or type, but I don't think it can do anything to fix column name/column type races since the type is not known at registration time.

I'd suggest making injections a dataset UDF.

**Comment by andrewelizondo** [comment]
2 things here: 1. we should expect more conflicts like this, targeting specific columns is very useful in many cases and not just for langkit udfs, and 2. whylogs should support multiple udfs targeted to the same column, this seems like a bug on whylogs that needs to be resolved asap.

**Comment by richard-rogers** [comment]
> 2 things here: 1. we should expect more conflicts like this, targeting specific columns is very useful in many cases and not just for langkit udfs, and 2. whylogs should support multiple udfs targeted to the same column, this seems like a bug on whylogs that needs to be resolved asap.

It supports multiple UDFs (all flavors) on a column. It does not support multiple instances of the same metric on a column, in this case the `UdfMetric`. The single `UdfMetric` instance can host lots of metric UDFs, but there can only be one instance of the metric itself per column. The problem is we were trying to stick 2 instances of the `UdfMetric` on the column, one by column name and one by column type. You'd have the same problem if you tried to create a schema that attached `DistributionMetric` by both column name and column type.

**Comment by richard-rogers** [comment]
I'm increasingly leaning towards deprecating `UdfMetric` and metric UDFs as the other flavors of UDF grow more capable.

**Comment by jamie256** [comment]
The load tests now pass when run altogether, there are some noisy errors/warnings logged which is related to this issue, but we can track the noisy output separately.
